# Generated by Django 6.0.2 on 2026-02-11 10:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water')], max_length=32)),
                ('meter_number', models.CharField(max_length=64)),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('location_note', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_meters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water')], max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('reading_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('currency', models.CharField(choices=[('JOD', 'JOD')], default='JOD', max_length=8)),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('ocr', 'OCR')], default='manual', max_length=16)),
                ('ocr_engine', models.CharField(blank=True, default='', max_length=32)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_ocr_text', models.TextField(blank=True, default='')),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='utility_bills.utilitymeter')),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.IntegerField()),
                ('current_reading', models.IntegerField()),
                ('billed_m3', models.IntegerField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water', to='utility_bills.utilitybill')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_previous', models.IntegerField()),
                ('import_current', models.IntegerField()),
                ('export_previous', models.IntegerField(blank=True, null=True)),
                ('export_current', models.IntegerField(blank=True, null=True)),
                ('billed_kwh', models.IntegerField(blank=True, null=True)),
                ('consumption_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('network_services_fees', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fixed_subsidy_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electricity', to='utility_bills.utilitybill')),
            ],
            options={
                'indexes': [models.Index(fields=['billed_kwh'], name='utility_bil_billed__97c801_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='utilitymeter',
            index=models.Index(fields=['user', 'utility_type'], name='utility_bil_user_id_ac629b_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitymeter',
            index=models.Index(fields=['meter_number'], name='utility_bil_meter_n_fa37a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='utilitymeter',
            unique_together={('user', 'utility_type', 'meter_number')},
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['user', 'utility_type'], name='utility_bil_user_id_fd33aa_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['meter', 'period_end'], name='utility_bil_meter_i_c85426_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['period_end'], name='utility_bil_period__5285fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='utilitybill',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('-999999999.999'))), name='ub_total_amount_reasonable'),
        ),
        migrations.AddIndex(
            model_name='waterbill',
            index=models.Index(fields=['billed_m3'], name='utility_bil_billed__96bb08_idx'),
        ),
    ]
